### ISSUE TITLE
Add a permissive license

### ISSUE THREAD

**Issue by arukuka** [brantburnett/couchbasefakeit#36]
Hello, @brantburnett .  
Thank you for the nice Docker image and script.  
My company is developing software including your scripts, and would like to publish it as OSS licensed under Apache 2.0 . 
Could you please place a permissive license on this repository?

**Comment by brantburnett** [comment]
Done, thanks for pointing out that I forgotten to add it.

**Comment by arukuka** [comment]
Thank you for your prompt response!
